#!/usr/bin/env bash
# This script stops the running 4-to_infinity_and_beyond process by killing its PID

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If PID found, kill the process
if [ -n "$pid" ]; then
  kill "$pid"
fi
