#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall commands

# Get the PID of the running 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If PID exists, use Perl to send TERM signal to the process
if [ -n "$pid" ]; then
  perl -e "kill 'TERM', $pid"
fi
