#!/usr/bin/env bash

# Find the PID of the running 7-highlander process
pid=$(pgrep -f 7-highlander)

# If PID exists, send SIGTERM via Perl's kill syscall
if [ -n "$pid" ]; then
  perl -e "kill 'TERM', $pid"
fi
